# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answerer', '0002_questionvectorized'),
    ]

    operations = [
        migrations.AddField(
            model_name='questionvectorized',
            name='original',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='answerer.Question'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questionvectorized',
            name='answer',
            field=models.CharField(max_length=1200),
        ),
        migrations.AlterField(
            model_name='questionvectorized',
            name='question',
            field=models.CharField(max_length=1200),
        ),
    ]
