# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-12 16:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('answerer', '0003_auto_20171112_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionPreprocessed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=1200)),
                ('answer', models.CharField(max_length=1200)),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answerer.Question')),
            ],
        ),
    ]
