# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-22 19:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answerer', '0005_questiond2vpreprocessed'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='questiond2vpreprocessed',
            name='original',
        ),
        migrations.RemoveField(
            model_name='questionvectorized',
            name='original',
        ),
        migrations.DeleteModel(
            name='QuestionD2VPreprocessed',
        ),
        migrations.DeleteModel(
            name='QuestionVectorized',
        ),
    ]
